process_stage: APPLY
source_name: Greene_Homes_Bigconfig
row_creation_time_upserted_count: 4
created_metric_count: 2
updated_metric_count: 8
deleted_metric_count: 0
unchanged_metric_count: 0
row_creation_time_upsert_failure_count: 0
metric_application_error_count: 0
invalid_asset_identifier_count: 0
total_error_count: 0
row_creation_time_report:
  columns_set_as_row_creation_time:
  - id: 72919918
    display_name: GREENE_HOMES_DEMO_STANDARD.STAGE.CONTRACT.UPDATE_DATETIME
  - id: 72919903
    display_name: GREENE_HOMES_DEMO_STANDARD.STAGE.CUSTOMER.UPDATE_DATETIME
  - id: 72919894
    display_name: GREENE_HOMES_DEMO_STANDARD.STAGE.CONTRACT_STATUS.STATUS_DATETIME
  - id: 72919923
    display_name: GREENE_HOMES_DEMO_STANDARD.STAGE.PAYMENTS.PAYMENT_DATETIME
metric_application_errors: []
invalid_asset_identifier_errors: []
created_metrics:
- metric_configuration:
    id: 124567871
    schedule_frequency:
      interval_type: HOURS_TIME_INTERVAL_TYPE
      interval_value: 24
    thresholds:
    - constant_threshold:
        bound:
          bound_type: LOWER_BOUND_SIMPLE_BOUND_TYPE
    - constant_threshold:
        bound:
          bound_type: UPPER_BOUND_SIMPLE_BOUND_TYPE
          value: 2.0
    warehouse_id: 1021
    dataset_id: 3561983
    metric_type:
      predefined_metric:
        metric_name: STRING_LENGTH_MAX
    parameters:
    - key: arg1
      column_name: BILLING_STATE
    lookback:
      interval_type: DAYS_TIME_INTERVAL_TYPE
      interval_value: 2
    lookback_type: DATA_TIME_LOOKBACK_TYPE
    metric_creation_state: METRIC_CREATION_STATE_SUITE
    grain_seconds: 86400
  collection_ids:
  - 1346
- metric_configuration:
    id: 124567872
    schedule_frequency:
      interval_type: HOURS_TIME_INTERVAL_TYPE
      interval_value: 24
    filters:
    - BUILD_STATE IS NOT NULL
    group_bys:
    - BUILD_STATE
    thresholds:
    - constant_threshold:
        bound:
          bound_type: LOWER_BOUND_SIMPLE_BOUND_TYPE
          value: 151000.0
    - constant_threshold:
        bound:
          bound_type: UPPER_BOUND_SIMPLE_BOUND_TYPE
          value: 1000000.0
    warehouse_id: 1021
    dataset_id: 3561984
    metric_type:
      predefined_metric:
        metric_name: MIN
    parameters:
    - key: arg1
      column_name: CONTRACT_PRICE
    lookback:
      interval_type: DAYS_TIME_INTERVAL_TYPE
      interval_value: 2
    lookback_type: DATA_TIME_LOOKBACK_TYPE
    metric_creation_state: METRIC_CREATION_STATE_SUITE
    grain_seconds: 86400
    name: Min Contract Price Per State
    description: The minimum contract price per state should never be below 150k.
  collection_ids:
  - 1346
updated_metrics:
- metric_configuration:
    id: 124567862
    schedule_frequency:
      interval_type: HOURS_TIME_INTERVAL_TYPE
      interval_value: 24
    thresholds:
    - auto_threshold:
        bound:
          bound_type: LOWER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    - auto_threshold:
        bound:
          bound_type: UPPER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    warehouse_id: 1021
    dataset_id: 3561982
    metric_type:
      predefined_metric:
        metric_name: COUNT_ROWS
    parameters:
    - key: arg1
      column_name: STATUS_ID
    lookback:
      interval_type: DAYS_TIME_INTERVAL_TYPE
      interval_value: 2
    lookback_type: DATA_TIME_LOOKBACK_TYPE
    metric_creation_state: METRIC_CREATION_STATE_SUITE
    grain_seconds: 86400
    is_table_metric: true
  collection_ids:
  - 1345
- metric_configuration:
    id: 124567863
    schedule_frequency:
      interval_type: HOURS_TIME_INTERVAL_TYPE
      interval_value: 24
    thresholds:
    - auto_threshold:
        bound:
          bound_type: LOWER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    - auto_threshold:
        bound:
          bound_type: UPPER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    warehouse_id: 1021
    dataset_id: 3561983
    metric_type:
      predefined_metric:
        metric_name: COUNT_ROWS
    parameters:
    - key: arg1
      column_name: CUSTOMER_ID
    lookback:
      interval_type: DAYS_TIME_INTERVAL_TYPE
      interval_value: 2
    lookback_type: DATA_TIME_LOOKBACK_TYPE
    metric_creation_state: METRIC_CREATION_STATE_SUITE
    grain_seconds: 86400
    is_table_metric: true
  collection_ids:
  - 1345
- metric_configuration:
    id: 124567864
    schedule_frequency:
      interval_type: HOURS_TIME_INTERVAL_TYPE
      interval_value: 24
    thresholds:
    - auto_threshold:
        bound:
          bound_type: LOWER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    - auto_threshold:
        bound:
          bound_type: UPPER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    warehouse_id: 1021
    dataset_id: 3561984
    metric_type:
      predefined_metric:
        metric_name: COUNT_ROWS
    parameters:
    - key: arg1
      column_name: CONTRACT_ID
    lookback:
      interval_type: DAYS_TIME_INTERVAL_TYPE
      interval_value: 2
    lookback_type: DATA_TIME_LOOKBACK_TYPE
    metric_creation_state: METRIC_CREATION_STATE_SUITE
    grain_seconds: 86400
    is_table_metric: true
  collection_ids:
  - 1345
- metric_configuration:
    id: 124567865
    schedule_frequency:
      interval_type: HOURS_TIME_INTERVAL_TYPE
      interval_value: 24
    thresholds:
    - auto_threshold:
        bound:
          bound_type: LOWER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    - auto_threshold:
        bound:
          bound_type: UPPER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    warehouse_id: 1021
    dataset_id: 3561985
    metric_type:
      predefined_metric:
        metric_name: COUNT_ROWS
    parameters:
    - key: arg1
      column_name: PAYMENT_ID
    lookback:
      interval_type: DAYS_TIME_INTERVAL_TYPE
      interval_value: 2
    lookback_type: DATA_TIME_LOOKBACK_TYPE
    metric_creation_state: METRIC_CREATION_STATE_SUITE
    grain_seconds: 86400
    is_table_metric: true
  collection_ids:
  - 1345
- metric_configuration:
    id: 124567866
    schedule_frequency:
      interval_type: HOURS_TIME_INTERVAL_TYPE
      interval_value: 6
    thresholds:
    - auto_threshold:
        bound:
          bound_type: UPPER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    warehouse_id: 1021
    dataset_id: 3561982
    metric_type:
      predefined_metric:
        metric_name: HOURS_SINCE_MAX_TIMESTAMP
    parameters:
    - key: arg1
      column_name: STATUS_DATETIME
    lookback:
      interval_type: DAYS_TIME_INTERVAL_TYPE
      interval_value: 2
    lookback_type: DATA_TIME_LOOKBACK_TYPE
    metric_creation_state: METRIC_CREATION_STATE_SUITE
    grain_seconds: 86400
  collection_ids:
  - 1345
- metric_configuration:
    id: 124567867
    schedule_frequency:
      interval_type: HOURS_TIME_INTERVAL_TYPE
      interval_value: 6
    thresholds:
    - auto_threshold:
        bound:
          bound_type: UPPER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    warehouse_id: 1021
    dataset_id: 3561983
    metric_type:
      predefined_metric:
        metric_name: HOURS_SINCE_MAX_TIMESTAMP
    parameters:
    - key: arg1
      column_name: UPDATE_DATETIME
    lookback:
      interval_type: DAYS_TIME_INTERVAL_TYPE
      interval_value: 2
    lookback_type: DATA_TIME_LOOKBACK_TYPE
    metric_creation_state: METRIC_CREATION_STATE_SUITE
    grain_seconds: 86400
  collection_ids:
  - 1345
- metric_configuration:
    id: 124567868
    schedule_frequency:
      interval_type: HOURS_TIME_INTERVAL_TYPE
      interval_value: 6
    thresholds:
    - auto_threshold:
        bound:
          bound_type: UPPER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    warehouse_id: 1021
    dataset_id: 3561984
    metric_type:
      predefined_metric:
        metric_name: HOURS_SINCE_MAX_TIMESTAMP
    parameters:
    - key: arg1
      column_name: UPDATE_DATETIME
    lookback:
      interval_type: DAYS_TIME_INTERVAL_TYPE
      interval_value: 2
    lookback_type: DATA_TIME_LOOKBACK_TYPE
    metric_creation_state: METRIC_CREATION_STATE_SUITE
    grain_seconds: 86400
  collection_ids:
  - 1345
- metric_configuration:
    id: 124567869
    schedule_frequency:
      interval_type: HOURS_TIME_INTERVAL_TYPE
      interval_value: 6
    thresholds:
    - auto_threshold:
        bound:
          bound_type: UPPER_BOUND_SIMPLE_BOUND_TYPE
          value: -1.0
        model_type: BOOTSTRAP_THRESHOLD_MODEL_TYPE
        sensitivity: AUTOTHRESHOLD_SENSITIVITY_MEDIUM
        forecast_value: -1.0
    warehouse_id: 1021
    dataset_id: 3561985
    metric_type:
      predefined_metric:
        metric_name: HOURS_SINCE_MAX_TIMESTAMP
    parameters:
    - key: arg1
      column_name: PAYMENT_DATETIME
    lookback:
      interval_type: DAYS_TIME_INTERVAL_TYPE
      interval_value: 2
    lookback_type: DATA_TIME_LOOKBACK_TYPE
    metric_creation_state: METRIC_CREATION_STATE_SUITE
    grain_seconds: 86400
  collection_ids:
  - 1345
deleted_metrics: []
unchanged_metrics: []
